env:
  global:
    - DOCKER_REPO=quay.io/kubevirt

language: go
go_import_path: kubevirt.io/hostpath-provisioner-operator
go:
  - 1.13.1

services:
- docker

install:
  - go get -u github.com/mgechev/revive

before_script:
  - make test

before_deploy:
  - docker login quay.io -u="$QUAY_USER" -p="$QUAY_PASS"

deploy:
# Release :latest images
- provider: script
  env:
    - TAG=latest
  script: make push
  skip_cleanup: true
  on:
    branch: master
    repo: kubevirt/hostpath-provisioner-operator
# Release versioned images
- provider: script
  env:
    - TAG=$TRAVIS_TAG
  script: make push
  branches:
      only: /v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+){0,1}/
  on:
    tags: true
    repo: kubevirt/hostpath-provisioner-operator
- provider: releases
  branches:
    only: /v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+){0,1}/
  on:
    tags: true
    repo: kubevirt/hostpath-provisioner-operator
  api_key:
    secure: tCx2plE1QqhFxMzKv9BmgeMv65jKLRrkqFMoM6YhQZ9lgop5bh6rz0VgH2DhUjwORem/TbI74SnBr5GhgnaZ0ihUHX/90Tgmq6g18ZcDq0/9LxcDaJd2Egf3akMx2wr/MEhIvnDuD+C18jDByAvtmfh4AtgzF7Gpgn2gaSsr9S7DLkaA4dJEkV+hI7wbJl6PjNevHCmgGQiIbwW/sNXyxjgFxnjODDK7lEr4ryWBD+IlAVsxeiA4jwrQigIEoZNzhJJ8VzWSZ8a0kxvWIxt0eSiGAGKiU1UP9oUi+ZyuwHRwouITDoilpZaGGhcc82pWemc4FM6kLMkEN6iY4fEC3MJ+spnDZKhc8mujlSbRsUADW0WxcWPx1KGgS/878LqyJZ0p7CrDwMg63RGmgThLl4VSTGvYcX0K4PK7ma5U10qHGCkTrG3yeiUOFRElUk0aS5KjGJ50GRkwbWyBdjZFbjTvT4sjszNcWycDhtvc/XghYDwTmKHUyr6kkmplEMb4gh5m5dtMnU1xhzrwwK9GaGlMikplk5XOUhogIwZqA+vUdEDhR8DIA3dy4BD17h3Suk0x2s6HCkSP6MSOCDLoNI+be3VLjATLwzc23/8kLDU/XbNjOwa5U21f+5Bj8pBWegnU1c2BJarLXcWQfpGELqHbrbCZhBVhzes5+T6sruc=
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - deploy/*.yaml
  - deploy/crds/*.yaml
